events {}

http {
    client_max_body_size 10M;

    upstream authentication-service {
        server authentication-service:3000;
    }

    upstream user-service {
        server user-service:3001;
    }

    upstream company-service {
        server company-service:3002;
    }

    upstream storage-service {
        server storage-service:3000;
    }

    upstream email-management-service {
        server email-management-service:3003;
    }

    upstream mapbox-service {
        server mapbox-service:3004;
    }

    upstream swagger-service {
        server swagger-service:3005;
    }

    upstream i18n-translation-service {
        server i18n-translation-service:3006;
    }

    include /etc/nginx/conf.d/*.conf;
}
