events {}

http {
    client_max_body_size 10M;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    # Carrega apenas app.conf (evita default do image com root /etc/nginx/html)
    include /etc/nginx/conf.d/app.conf;
}
